### ISSUE TITLE
Sugestão

### ISSUE THREAD

**Issue by samverneck** [st1s/angular-starter-boilerplate#1]
Opa!!
Pq não experimenta o yarn cara? Dê uma testada nele nesse projeto e em outros. ;)
Abraço!!!

**Comment by stewones** [comment]
Pq agora uso angular cli pra tudo 🙃

**Comment by stewones** [comment]
na vdd nunca usei yarn, agora q vi q eh um gerenciador de pacotes tbm.. vc pode usar tranquilo. vou aceitar o PR mas esse repo ta deprecated pq agora uso somente o angular cli pra levantar a app, gerar build, pwa's, etc.
